### ISSUE TITLE
Exception in thread "tend" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Asisranjan** [aerospike/aerospike-client-java#159]
Sometime we are able to see following exception
Exception in thread "tend" java.lang.OutOfMemoryError: Java heap space
at com.aerospike.client.util.ThreadLocalData.resizeBuffer(ThreadLocalData.java:65)
at com.aerospike.client.Info.resizeBuffer(Info.java:587)
at com.aerospike.client.Info.sendCommand(Info.java:576)
at com.aerospike.client.Info.<init>(Info.java:86)
at com.aerospike.client.cluster.PeerParser.<init>(PeerParser.java:43)
at com.aerospike.client.cluster.Node.refreshPeers(Node.java:357)
at com.aerospike.client.cluster.Cluster.tend(Cluster.java:451)
at com.aerospike.client.cluster.Cluster.run(Cluster.java:405)
at java.lang.Thread.run(Thread.java:748)
Exception in thread "tend" java.lang.OutOfMemoryError: Java heap space
at com.aerospike.client.util.ThreadLocalData.resizeBuffer(ThreadLocalData.java:65)
at com.aerospike.client.Info.resizeBuffer(Info.java:587)
at com.aerospike.client.Info.sendCommand(Info.java:576)
at com.aerospike.client.Info.<init>(Info.java:124)
at com.aerospike.client.Info.request(Info.java:521)
at com.aerospike.client.cluster.Node.refresh(Node.java:170)
at com.aerospike.client.cluster.Cluster.tend(Cluster.java:442)
at com.aerospike.client.cluster.Cluster.run(Cluster.java:405)
at java.lang.Thread.run(Thread.java:748)

Can anyone please explain the cause of the above exception?

**Comment by BrianNichols** [comment]
A cluster tend thread runs in the background for every AerospikeClient instance.  This thread periodically requests cluster status from all server nodes.  One of these requests (which is very small in memory size) is failing due to lack of memory.

I suggest subscribing to the debug log.  A debug message is generated with the size requested when thread local buffers are resized.

```
public class MyConsole implements Log.Callback {
      public MyConsole() {
          Log.setLevel(Log.Level.DEBUG);
          Log.setCallback(this);
      }

      @Override
      public void log(Log.Level level, String message) {
          // Write log messages to the appropriate place.
      }
  }
```
